import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'ps' | 'fa';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  isRTL: boolean;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    appName: 'TopUpHub',
    home: 'Home',
    transactions: 'Transactions',
    suppliers: 'Suppliers',
    resellers: 'Resellers',
    reports: 'Reports',
    login: 'Login',
    register: 'Register',
    forgotPassword: 'Forgot Password',
    totalBalance: 'Total Balance',
    supplierDue: 'Supplier Due',
    resellerDue: 'Reseller Due',
    todayProfit: "Today's Profit",
    buyTopup: 'Buy Topup',
    sellTopup: 'Sell Topup',
    supplierPayment: 'Supplier Payment',
    resellerPayment: 'Reseller Payment',
    addSupplier: 'Add Supplier',
    addReseller: 'Add Reseller',
    recentTransactions: 'Recent Transactions',
    quickActions: 'Quick Actions',
    supplierName: 'Supplier Name',
    company: 'Company',
    phone: 'Phone',
    bonusPercentage: 'Bonus %',
    status: 'Status',
    active: 'Active',
    inactive: 'Inactive',
    view: 'View',
    edit: 'Edit',
    disable: 'Disable',
    resellerName: 'Reseller Name',
    city: 'City',
    creditLimit: 'Credit Limit',
    baseAmount: 'Base Amount',
    referenceNumber: 'Reference Number',
    notes: 'Notes',
    totalTopup: 'Total Topup',
    bonus: 'Bonus',
    calculate: 'Calculate',
    submit: 'Submit',
    partyName: 'Party Name',
    transactionType: 'Transaction Type',
    debit: 'Debit',
    credit: 'Credit',
    balance: 'Balance',
    date: 'Date',
    all: 'All',
    purchases: 'Purchases',
    sales: 'Sales',
    payments: 'Payments',
    search: 'Search...',
    totalPurchased: 'Total Purchased',
    totalPaid: 'Total Paid',
    totalSold: 'Total Sold',
    totalReceived: 'Total Received',
    monthlyPurchase: 'Monthly Purchase',
    monthlySales: 'Monthly Sales',
    monthlyProfit: 'Monthly Profit',
    name: 'Name',
    businessName: 'Business Name',
    password: 'Password',
    phoneOrEmail: 'Phone or Email',
    createAccount: 'Create Account',
    signIn: 'Sign In',
    resetPassword: 'Reset Password',
    sendResetLink: 'Send Reset Link',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: "Don't have an account?",
    forgotPasswordQ: 'Forgot password?',
    supplierLedger: 'Supplier Ledger',
    resellerLedger: 'Reseller Ledger',
    selectSupplier: 'Select Supplier',
    selectReseller: 'Select Reseller',
    companyName: 'Company Name',
    liveCalculation: 'Live Calculation',
    welcomeBack: 'Welcome back',
    manageYourBusiness: 'Manage your wholesale top-up business',
    phoneRequired: 'Phone number or email is required',
    passwordRequired: 'Password is required',
    loginSuccess: 'Login successful!',
    signingIn: 'Signing in...',
    logout: 'Logout',
    profile: 'Profile',
    settings: 'Settings',
    logoutSuccess: 'Logged out successfully',
    searchSuppliers: 'Search suppliers...',
    noSuppliers: 'No suppliers found',
    activate: 'Activate',
    delete: 'Delete',
    previous: 'Previous',
    next: 'Next',
    supplierActivated: 'Supplier activated successfully',
    supplierDeactivated: 'Supplier deactivated successfully',
    supplierDeleted: 'Supplier deleted successfully',
    statusUpdateFailed: 'Failed to update supplier status',
    deleteFailed: 'Failed to delete supplier',
    viewingSupplier: 'Viewing supplier details',
    nameRequired: 'Supplier name is required',
    supplierPhoneRequired: 'Phone number is required',
    companyRequired: 'Company name is required',
    bonusRequired: 'Bonus percentage is required',
    invalidBonus: 'Please enter a valid bonus percentage',
    supplierUpdated: 'Supplier updated successfully',
    supplierCreated: 'Supplier created successfully',
    operationFailed: 'Operation failed',
    editSupplier: 'Edit Supplier',
    phoneHint: 'Include country code e.g. +93',
    bonusHint: 'Percentage of bonus on each purchase',
    cancel: 'Cancel',
    saving: 'Saving...',
    pending: 'Pending',
    updateBonus: 'Update %',
    updateBonusPercentage: 'Update Bonus Percentage',
    percentageUpdated: 'Bonus percentage updated successfully',
    updateFailed: 'Failed to update bonus percentage',
    updating: 'Updating...',
    update: 'Update',
    searchResellers: 'Search resellers...',
    noResellers: 'No resellers found',
    resellerActivated: 'Reseller activated successfully',
    resellerDeactivated: 'Reseller deactivated successfully',
    resellerDeleted: 'Reseller deleted successfully',
    viewingReseller: 'Viewing reseller details',
    cityRequired: 'City is required',
    resellerUpdated: 'Reseller updated successfully',
    resellerCreated: 'Reseller created successfully',
    editReseller: 'Edit Reseller',
    selectSupplierRequired: 'Please select a supplier',
    selectResellerRequired: 'Please select a reseller',
    validAmountRequired: 'Please enter a valid amount',
    topupPurchased: 'Topup purchased successfully',
    topupSold: 'Topup sold successfully',
    processing: 'Processing...',
    discount: 'Discount',
    finalAmount: 'Final Amount',
    referencePlaceholder: 'Enter reference number (optional)',
    notesPlaceholder: 'Enter notes (optional)',
    paidAmount: 'Paid Amount',
    paidAmountHint: 'Amount paid now (optional)',
    dueAmount: 'Due Amount',
    paid: 'Paid',
    checkingStock: 'Checking stock...',
    availableStock: 'Available Stock',
    insufficientStock: 'Insufficient stock! Available: {stock}',
    stockCheckFailed: 'Failed to check stock',
    stockWarning: '⚠️ Insufficient stock for this sale',
    stockSufficient: '✅ Stock remaining after sale: {remaining}',
    noTransactions: 'No transactions found',
    loading: 'Loading...',
    viewAll: 'View All',





    validPaidAmountRequired: 'Please enter a valid paid amount',
    paidExceedsTotal: 'Paid amount cannot exceed total topup amount',
    amountExceedsStock: 'Amount exceeds available stock ({stock})',

    baseAmountHint: 'This is the amount you pay to supplier',

    maxPossibleBase: 'Max possible',


    paidNow: 'Paid Now',
    dueToSupplier: 'Due to Supplier',
    dueFromReseller: 'Due from Reseller',


    exceedsStock: 'Exceeds stock!',
    insufficientStockWarning: 'Insufficient stock for this sale',
    stockAfterSale: 'Stock after sale',
    maxAmount: 'Max amount',

    confirmPurchase: 'Confirm Purchase',
    confirmSale: 'Confirm Sale',

    payDue: 'Pay Due',
    paymentAmount: 'Payment Amount',
    confirmPayment: 'Confirm Payment',
    paymentSuccessful: 'Payment recorded successfully',
    paymentFailed: 'Payment failed',
    paymentExceedsDue: 'Payment cannot exceed due amount ({due})',
    action: 'Action',
    pay: 'Pay',
    collectDue: 'Collect Due',
    collectionAmount: 'Collection Amount',
    confirmCollection: 'Confirm Collection',
    collectionSuccessful: 'Payment collected successfully',
    collectionFailed: 'Collection failed',
    collectionExceedsDue: 'Collection cannot exceed due amount ({due})',
    collect: 'Collect',

  },
  ps: {
    appName: 'ټاپ اپ هب',
    home: 'کور',
    transactions: 'راکړه ورکړه',
    suppliers: 'عرضه کوونکي',
    resellers: 'بیا پلورونکي',
    reports: 'راپورونه',
    login: 'ننوتل',
    register: 'راجسټر',
    forgotPassword: 'پټنوم مو هیر شوی؟',
    totalBalance: 'ټول بیلانس',
    supplierDue: 'د عرضه کوونکي پور',
    resellerDue: 'د بیا پلورونکي پور',
    todayProfit: 'نن ورځ ګټه',
    buyTopup: 'ټاپ اپ واخلئ',
    sellTopup: 'ټاپ اپ وپلورئ',
    supplierPayment: 'عرضه کوونکي ته تادیه',
    resellerPayment: 'بیا پلورونکي ته تادیه',
    addSupplier: 'عرضه کوونکی اضافه کړئ',
    addReseller: 'بیا پلورونکی اضافه کړئ',
    recentTransactions: 'وروستي راکړه ورکړه',
    quickActions: 'چټکې کړنې',
    supplierName: 'د عرضه کوونکي نوم',
    company: 'شرکت',
    phone: 'تلیفون',
    bonusPercentage: 'بونس ٪',
    status: 'حالت',
    active: 'فعال',
    inactive: 'غیر فعال',
    view: 'لیدل',
    edit: 'سمون',
    disable: 'غیر فعالول',
    resellerName: 'د بیا پلورونکي نوم',
    city: 'ښار',
    creditLimit: 'د پور حد',
    baseAmount: 'اصلي مبلغ',
    referenceNumber: 'حواله نمبر',
    notes: 'یادښتونه',
    totalTopup: 'ټول ټاپ اپ',
    bonus: 'بونس',
    calculate: 'حساب',
    submit: 'ولیږئ',
    partyName: 'د ګوند نوم',
    transactionType: 'د راکړې ورکړې ډول',
    debit: 'پور',
    credit: 'جمع',
    balance: 'بیلانس',
    date: 'نیټه',
    all: 'ټول',
    purchases: 'خریدونه',
    sales: 'پلورنه',
    payments: 'تادیات',
    search: 'لټون...',
    totalPurchased: 'ټول خریدونه',
    totalPaid: 'ټول تادیه شوي',
    totalSold: 'ټول پلورل شوي',
    totalReceived: 'ټول ترلاسه شوي',
    monthlyPurchase: 'میاشتنۍ خریدونه',
    monthlySales: 'میاشتنۍ پلورنه',
    monthlyProfit: 'میاشتنۍ ګټه',
    name: 'نوم',
    businessName: 'د سوداګرۍ نوم',
    password: 'پټنوم',
    phoneOrEmail: 'تلیفون یا ایمیل',
    createAccount: 'حساب جوړ کړئ',
    signIn: 'ننوتل',
    resetPassword: 'پټنوم بیا تنظیم',
    sendResetLink: 'لینک ولیږئ',
    alreadyHaveAccount: 'حساب لرئ؟',
    dontHaveAccount: 'حساب نه لرئ؟',
    forgotPasswordQ: 'پټنوم مو هیر شوی؟',
    supplierLedger: 'د عرضه کوونکي کھاتہ',
    resellerLedger: 'د بیا پلورونکي کھاتہ',
    selectSupplier: 'عرضه کوونکی وټاکئ',
    selectReseller: 'بیا پلورونکی وټاکئ',
    companyName: 'د شرکت نوم',
    liveCalculation: 'ژوندی حساب',
    welcomeBack: 'بیرته ښه راغلاست',
    manageYourBusiness: 'خپله عمده ټاپ اپ سوداګري اداره کړئ',
    phoneRequired: 'تلیفون یا ایمیل اړین دی',
    passwordRequired: 'پټنوم اړین دی',
    loginSuccess: 'بریالی ننوتل!',
    signingIn: 'ننوتل روان دي...',
    logout: 'وتل',
    profile: 'پروفایل',
    settings: 'تنظیمات',
    logoutSuccess: 'بریالي وتل',
    searchSuppliers: 'عرضه کوونکي ولټوئ...',
    noSuppliers: 'هیڅ عرضه کوونکی ونه موندل شو',
    activate: 'فعالول',
    delete: 'ړنګول',
    previous: 'مخکینی',
    next: 'راتلونکی',
    supplierActivated: 'عرضه کوونکی په بریالیتوب سره فعال شو',
    supplierDeactivated: 'عرضه کوونکی په بریالیتوب سره غیر فعال شو',
    supplierDeleted: 'عرضه کوونکی په بریالیتوب سره ړنګ شو',
    statusUpdateFailed: 'د وضعیت تازه کول ناکام شول',
    deleteFailed: 'ړنګول ناکام شول',
    viewingSupplier: 'د عرضه کوونکی تفصیلات لیدل',
    nameRequired: 'د عرضه کوونکی نوم اړین دی',
    supplierPhoneRequired: 'د تلیفون شمیره اړینه ده',
    companyRequired: 'د شرکت نوم اړین دی',
    bonusRequired: 'د بونس فیصدي اړینه ده',
    invalidBonus: 'مهرباني وکړئ سمه بونس فیصدي دننه کړئ',
    supplierUpdated: 'عرضه کوونکی په بریالیتوب سره تازه شو',
    supplierCreated: 'عرضه کوونکی په بریالیتوب سره جوړ شو',
    operationFailed: 'عملیات ناکام شول',
    editSupplier: 'د عرضه کوونکی سمول',
    phoneHint: 'د هیواد کوډ شامل کړئ لکه +93',
    bonusHint: 'په هر پیرود کې د بونس فیصدي',
    cancel: 'لغوه',
    saving: 'خوندي کول...',
    pending: 'انتظار',
    updateBonus: 'بونس بدلول',
    updateBonusPercentage: 'د بونس فیصدي بدلول',
    percentageUpdated: 'د بونس فیصدي په بریالیتوب سره تازه شوه',
    updateFailed: 'د بونس فیصدي تازه کول ناکام شول',
    updating: 'تازه کول...',
    update: 'تازه کول',
    searchResellers: 'بیا پلورونکي ولټوئ...',
    noResellers: 'هیڅ بیا پلورونکی ونه موندل شو',
    resellerActivated: 'بیا پلورونکی په بریالیتوب سره فعال شو',
    resellerDeactivated: 'بیا پلورونکی په بریالیتوب سره غیر فعال شو',
    resellerDeleted: 'بیا پلورونکی په بریالیتوب سره ړنګ شو',
    viewingReseller: 'د بیا پلورونکی تفصیلات لیدل',
    cityRequired: 'ښار اړین دی',
    resellerUpdated: 'بیا پلورونکی په بریالیتوب سره تازه شو',
    resellerCreated: 'بیا پلورونکی په بریالیتوب سره جوړ شو',
    editReseller: 'د بیا پلورونکی سمول',
    selectSupplierRequired: 'مهرباني وکړئ عرضه کوونکی وټاکئ',
    selectResellerRequired: 'مهرباني وکړئ بیا پلورونکی وټاکئ',
    validAmountRequired: 'مهرباني وکړئ سمه اندازه دننه کړئ',
    topupPurchased: 'ټاپ اپ په بریالیتوب سره وپلورل شو',
    topupSold: 'ټاپ اپ په بریالیتوب سره وپلورل شو',
    processing: 'پروسه کېږي...',
    discount: 'تخفیف',
    finalAmount: 'نهایی اندازه',
    referencePlaceholder: 'د حوالې نمبر دننه کړئ (اختیاري)',
    notesPlaceholder: 'یادښتونه دننه کړئ (اختیاري)',
    paidAmount: 'تادیه شوی مقدار',
    paidAmountHint: 'اوس تادیه شوی مقدار (اختیاري)',
    dueAmount: 'پاتې مقدار',
    paid: 'تادیه شوی',
    checkingStock: 'ستاک چک کول...',
    availableStock: 'موجوده ستاک',
    insufficientStock: 'کافي ستاک نشته! موجوده: {stock}',
    stockCheckFailed: 'ستاک چک کول ناکام شول',
    stockWarning: '⚠️ د پلور لپاره کافي ستاک نشته',
    stockSufficient: '✅ د پلور وروسته پاتې ستاک: {remaining}',
    noTransactions: 'هیڅ راکړه ورکړه ونه موندل شوه',
    loading: 'بار کول...',
    viewAll: 'ټول وګورئ',
   
    
    
    
    
    validPaidAmountRequired: 'مهرباني وکړئ سمه تادیه شوی اندازه دننه کړئ',
    paidExceedsTotal: 'تادیه شوی اندازه د ټول ټاپ اپ څخه زیات نشي کیدی',
    amountExceedsStock: 'اندازه د موجوده سټاک څخه زیاته ده ({stock})',
    
    // Hint Texts
    baseAmountHint: 'دا هغه اندازه ده چې تاسو عرضه کوونکي ته ورکوئ',
    
    maxPossibleBase: 'زیاته ممکنه اندازه',
    
    
    paidNow: 'اوس تادیه شوی',
    dueToSupplier: 'عرضه کوونکي ته پاتې',
    dueFromReseller: 'بیا پلورونکی پاتې دی',
    
    
    exceedsStock: 'له سټاک څخه زیات!',
    insufficientStockWarning: 'د دې پلور لپاره کافي سټاک نشته',
    stockAfterSale: 'د پلور وروسته سټاک',
    maxAmount: 'زیاته اندازه',
    
    confirmPurchase: 'خرید تایید کړئ',
    confirmSale: 'پلور تایید کړئ',
    payDue: 'پاتې پیسې ادا کړئ',
    paymentAmount: 'د تادیې مقدار',
    confirmPayment: 'تادیه تایید کړئ',
    paymentSuccessful: 'تادیه په بریالیتوب سره ثبت شوه',
    paymentFailed: 'تادیه ناکامه شوه',
    paymentExceedsDue: 'تادیه د پاتې پیسو څخه زیات نشي کیدی ({due})',
    action: 'عمل',
    pay: 'ادا کړئ',
    collectDue: 'پاتې پیسې راټول کړئ',
    collectionAmount: 'د راټولولو مقدار',
    confirmCollection: 'راټولول تایید کړئ',
    collectionSuccessful: 'تادیه په بریالیتوب سره راټوله شوه',
    collectionFailed: 'راټولول ناکام شو',
    collectionExceedsDue: 'راټولول د پاتې پیسو څخه زیات نشي کیدی ({due})',
    collect: 'راټول کړئ',
    
  },
  fa: {
    appName: 'تاپ آپ هاب',
    home: 'خانه',
    transactions: 'تراکنش‌ها',
    suppliers: 'تامین‌کنندگان',
    resellers: 'فروشندگان',
    reports: 'گزارش‌ها',
    login: 'ورود',
    register: 'ثبت نام',
    forgotPassword: 'رمز عبور را فراموش کردید؟',
    totalBalance: 'موجودی کل',
    supplierDue: 'بدهی تامین‌کننده',
    resellerDue: 'بدهی فروشنده',
    todayProfit: 'سود امروز',
    buyTopup: 'خرید شارژ',
    sellTopup: 'فروش شارژ',
    supplierPayment: 'پرداخت تامین‌کننده',
    resellerPayment: 'پرداخت فروشنده',
    addSupplier: 'افزودن تامین‌کننده',
    addReseller: 'افزودن فروشنده',
    recentTransactions: 'تراکنش‌های اخیر',
    quickActions: 'عملیات سریع',
    supplierName: 'نام تامین‌کننده',
    company: 'شرکت',
    phone: 'تلفن',
    bonusPercentage: 'درصد پاداش',
    status: 'وضعیت',
    active: 'فعال',
    inactive: 'غیرفعال',
    view: 'مشاهده',
    edit: 'ویرایش',
    disable: 'غیرفعال',
    resellerName: 'نام فروشنده',
    city: 'شهر',
    creditLimit: 'سقف اعتبار',
    baseAmount: 'مبلغ پایه',
    referenceNumber: 'شماره مرجع',
    notes: 'یادداشت',
    totalTopup: 'کل شارژ',
    bonus: 'پاداش',
    calculate: 'محاسبه',
    submit: 'ارسال',
    partyName: 'نام طرف',
    transactionType: 'نوع تراکنش',
    debit: 'بدهکار',
    credit: 'بستانکار',
    balance: 'موجودی',
    date: 'تاریخ',
    all: 'همه',
    purchases: 'خرید',
    sales: 'فروش',
    payments: 'پرداخت‌ها',
    search: 'جستجو...',
    totalPurchased: 'کل خرید',
    totalPaid: 'کل پرداخت',
    totalSold: 'کل فروش',
    totalReceived: 'کل دریافت',
    monthlyPurchase: 'خرید ماهانه',
    monthlySales: 'فروش ماهانه',
    monthlyProfit: 'سود ماهانه',
    name: 'نام',
    businessName: 'نام کسب و کار',
    password: 'رمز عبور',
    phoneOrEmail: 'تلفن یا ایمیل',
    createAccount: 'ایجاد حساب',
    signIn: 'ورود',
    resetPassword: 'بازنشانی رمز',
    sendResetLink: 'ارسال لینک',
    alreadyHaveAccount: 'حساب دارید؟',
    dontHaveAccount: 'حساب ندارید؟',
    forgotPasswordQ: 'رمز را فراموش کردید؟',
    supplierLedger: 'دفتر تامین‌کننده',
    resellerLedger: 'دفتر فروشنده',
    selectSupplier: 'تامین‌کننده را انتخاب کنید',
    selectReseller: 'فروشنده را انتخاب کنید',
    companyName: 'نام شرکت',
    liveCalculation: 'محاسبه زنده',
    welcomeBack: 'خوش آمدید',
    manageYourBusiness: 'کسب و کار شارژ عمده خود را مدیریت کنید',
    phoneRequired: 'تلفن یا ایمیل الزامی است',
    passwordRequired: 'رمز عبور الزامی است',
    loginSuccess: 'ورود موفق!',
    signingIn: 'در حال ورود...',
    logout: 'خروج',
    profile: 'پروفایل',
    settings: 'تنظیمات',
    logoutSuccess: 'خروج موفق',
    searchSuppliers: 'جستجوی تامین‌کنندگان...',
    noSuppliers: 'تامین‌کننده‌ای یافت نشد',
    activate: 'فعال کردن',
    delete: 'حذف',
    previous: 'قبلی',
    next: 'بعدی',
    supplierActivated: 'تامین‌کننده با موفقیت فعال شد',
    supplierDeactivated: 'تامین‌کننده با موفقیت غیرفعال شد',
    supplierDeleted: 'تامین‌کننده با موفقیت حذف شد',
    statusUpdateFailed: 'به‌روزرسانی وضعیت ناموفق بود',
    deleteFailed: 'حذف ناموفق بود',
    viewingSupplier: 'در حال مشاهده جزئیات تامین‌کننده',
    nameRequired: 'نام تامین‌کننده الزامی است',
    supplierPhoneRequired: 'شماره تلفن الزامی است',
    companyRequired: 'نام شرکت الزامی است',
    bonusRequired: 'درصد پاداش الزامی است',
    invalidBonus: 'لطفاً درصد پاداش معتبر وارد کنید',
    supplierUpdated: 'تامین‌کننده با موفقیت به‌روزرسانی شد',
    supplierCreated: 'تامین‌کننده با موفقیت ایجاد شد',
    operationFailed: 'عملیات ناموفق بود',
    editSupplier: 'ویرایش تامین‌کننده',
    phoneHint: 'کد کشور را وارد کنید مانند +93',
    bonusHint: 'درصد پاداش در هر خرید',
    cancel: 'انصراف',
    saving: 'در حال ذخیره...',
    pending: 'در انتظار',
    updateBonus: 'به‌روزرسانی %',
    updateBonusPercentage: 'به‌روزرسانی درصد پاداش',
    percentageUpdated: 'درصد پاداش با موفقیت به‌روزرسانی شد',
    updateFailed: 'به‌روزرسانی درصد پاداش ناموفق بود',
    updating: 'در حال به‌روزرسانی...',
    update: 'به‌روزرسانی',
    searchResellers: 'جستجوی فروشندگان...',
    noResellers: 'فروشنده‌ای یافت نشد',
    resellerActivated: 'فروشنده با موفقیت فعال شد',
    resellerDeactivated: 'فروشنده با موفقیت غیرفعال شد',
    resellerDeleted: 'فروشنده با موفقیت حذف شد',
    viewingReseller: 'در حال مشاهده جزئیات فروشنده',
    cityRequired: 'شهر الزامی است',
    resellerUpdated: 'فروشنده با موفقیت به‌روزرسانی شد',
    resellerCreated: 'فروشنده با موفقیت ایجاد شد',
    editReseller: 'ویرایش فروشنده',
    selectSupplierRequired: 'لطفاً یک تامین‌کننده انتخاب کنید',
    selectResellerRequired: 'لطفاً یک فروشنده انتخاب کنید',
    validAmountRequired: 'لطفاً مبلغ معتبر وارد کنید',
    topupPurchased: 'شارژ با موفقیت خریداری شد',
    topupSold: 'شارژ با موفقیت فروخته شد',
    processing: 'در حال پردازش...',
    discount: 'تخفیف',
    finalAmount: 'مبلغ نهایی',
    referencePlaceholder: 'شماره مرجع را وارد کنید (اختیاری)',
    notesPlaceholder: 'یادداشت وارد کنید (اختیاری)',
    paidAmount: 'مبلغ پرداخت شده',
    paidAmountHint: 'مبلغ پرداخت شده (اختیاری)',
    dueAmount: 'مبلغ باقیمانده',
    paid: 'پرداخت شده',
    checkingStock: 'بررسی موجودی...',
    availableStock: 'موجودی قابل فروش',
    insufficientStock: 'موجودی ناکافی! موجودی: {stock}',
    stockCheckFailed: 'بررسی موجودی ناموفق بود',
    stockWarning: '⚠️ موجودی برای این فروش کافی نیست',
    stockSufficient: '✅ موجودی پس از فروش: {remaining}',
    noTransactions: 'تراکنشی یافت نشد',
    loading: 'در حال بارگذاری...',
    viewAll: 'مشاهده همه',

    
    
    
    
    validPaidAmountRequired: 'لطفاً یک مبلغ پرداخت معتبر وارد کنید',
    paidExceedsTotal: 'مبلغ پرداخت شده نمی‌تواند از کل شارژ بیشتر باشد',
    amountExceedsStock: 'مبلغ از موجودی انبار بیشتر است ({stock})',
    
    // Hint Texts
    baseAmountHint: 'این مبلغی است که به تامین‌کننده پرداخت می‌کنید',
    
    maxPossibleBase: 'حداکثر ممکن',
    
    
    paidNow: 'پرداخت شده',
    dueToSupplier: 'بدهی به تامین‌کننده',
    dueFromReseller: 'بدهی فروشنده',
    
    
    exceedsStock: 'بیشتر از موجودی!',
    insufficientStockWarning: 'موجودی برای این فروش کافی نیست',
    stockAfterSale: 'موجودی پس از فروش',
    maxAmount: 'حداکثر مبلغ',
    
    
    confirmPurchase: 'تایید خرید',
    confirmSale: 'تایید فروش',
    payDue: 'پرداخت بدهی',
    paymentAmount: 'مبلغ پرداخت',
    confirmPayment: 'تایید پرداخت',
    paymentSuccessful: 'پرداخت با موفقیت ثبت شد',
    paymentFailed: 'پرداخت ناموفق بود',
    paymentExceedsDue: 'پرداخت نمی‌تواند از مبلغ بدهی بیشتر باشد ({due})',
    action: 'عملیات',
    pay: 'پرداخت',
    collectDue: 'دریافت بدهی',
    collectionAmount: 'مبلغ دریافت',
    confirmCollection: 'تایید دریافت',
    collectionSuccessful: 'پرداخت با موفقیت دریافت شد',
    collectionFailed: 'دریافت ناموفق بود',
    collectionExceedsDue: 'دریافت نمی‌تواند از مبلغ بدهی بیشتر باشد ({due})',
    collect: 'دریافت',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');
  const isRTL = language === 'ps' || language === 'fa';

  useEffect(() => {
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, isRTL, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};
